---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - livefire_answerfile.yml
  tasks:
    - name: Check manager status
      nsxt_manager_status:
          hostname: "{{hostname}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: False
          wait_time: 50

    - name: Deploy compute manager
      nsxt_fabric_compute_managers:
          hostname: "{{hostname}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: False
          display_name: "vcsa-01a"
          server: "192.168.110.22"
          origin_type: vCenter
          credential:
            credential_type: UsernamePasswordLoginCredential
            username: "administrator@vsphere.local"
            password: "VMware1!"
            thumbprint: "DA:86:AF:44:45:AB:B1:EB:50:E1:C8:84:5B:DF:DB:D1:35:76:FF:AF:B5:39:AC:35:F8:B3:3C:8C:E1:1B:A3:8B"
          state: present
      register: compute_manager

    - name: Enable auto install of NSX for specified clusters
      nsxt_compute_collection_fabric_templates:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "Cluster_01a-fabric_template"
        compute_manager_name: "vcsa-01a"
        cluster_name: "Cluster-01a"
        auto_install_nsx: True
        state: present
      with_items:
        - "Cluster-01a"
      register: auto_install_nsx_result

    - name: Create uplink profile for ESXi hosts
      nsxt_uplink_profiles:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        resource_type: UplinkHostSwitchProfile
        display_name: "{{item.display_name}}"
        mtu: 1700
        teaming: "{{item.teaming}}"
        transport_vlan: "{{item.transport_vlan}}"
        state: "present"
      with_items:
        - "{{uplink_profiles_hosts}}"

    - name: Create VLAN transport zone
      nsxt_transport_zones:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        resource_type: "TransportZone"
        display_name: "{{item.display_name}}"
        description: ""
        transport_type: "{{item.transport_type}}"
        host_switch_name: "{{item.host_switch_name}}"
        state: "present"
      with_items:
        - "{{vlan_transportzones}}"

    - name: Create ip pool for TEP interfaces
      nsxt_ip_pools:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "{{item.display_name}}"
        subnets: "{{item.subnets}}"
        state: present
      with_items:
        - "{{ip_pools}}"


    - name: Enable auto creation of transport nodes for specified clusters
      nsxt_compute_collection_transport_templates:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "Cluster_01a-transport_template"
        compute_collections:
        - compute_manager_name: "vcsa-01a"
          cluster_name: "Cluster-01a"
        host_switch_spec:
            resource_type: StandardHostSwitchSpec
            host_switches:
            - host_switch_profiles:
              - name: "{{uplink_profiles_hosts[0].display_name}}"
                type: UplinkHostSwitchProfile
              host_switch_name: "{{vlan_transportzones[0].host_switch_name}}"
              pnics:
              - device_name: vmnic1
                uplink_name: "uplink-1"
              - device_name: vmnic2
                uplink_name: "uplink-2"
              ip_assignment_spec:
                resource_type: StaticIpPoolSpec
                ip_pool_name: "{{ip_pools[0].display_name}}"
        transport_zone_endpoints:
        - transport_zone_name: "{{vlan_transportzones[0].display_name}}"
        state: present

    - name: "Create VLAN Logical Switches for 4 Tiers Application"
      nsxt_logical_switches:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "{{item.display_name}}"
        replication_mode: SOURCE
        admin_state: UP
        transport_zone_name: "{{vlan_transportzones[0].display_name}}"
        vlan: "{{item.vlan_id}}"
        state: "present"
      with_items:
        - "{{application_vlans}}"


