---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - livefire_answerfile.yml
  tasks:
    - name: Check manager status
      nsxt_manager_status:
          hostname: "{{hostname}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: False
          wait_time: 50


    - name: Create T0 logical router for K8S
      nsxt_logical_routers:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "t0-K8S"
        edge_cluster_name: edge-cluster-1-SiteA
        router_type: TIER0
        high_availability_mode: ACTIVE_STANDBY
        state: "present"
      register: t0

    - name: Create first logical port on EXT1_VLAN LS to connect T0 router
      nsxt_logical_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "T0K8S-Ext1LpA"
        logical_switch_name: "VLAN-Ext1Ls"
        admin_state: UP
        state: "present"
      register: lsp_T0_EXT1a


    - name: Create first logical port on EXT2_VLAN LS to connect T0 router
      nsxt_logical_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "T0K8S-Ext2LpA"
        logical_switch_name: "VLAN-Ext2Ls"
        admin_state: UP
        state: "present"
      register: lsp_T0_EXT2a


    - name: Create second logical port on EXT1_VLAN LS to connect T0 router
      nsxt_logical_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "T0K8S-Ext1LpB"
        logical_switch_name: "VLAN-Ext1Ls"
        admin_state: UP
        state: "present"
      register: lsp_T0_EXT1b

    - name: Create second logical port on EXT2_VLAN LS to connect T0 router
      nsxt_logical_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "T0K8S-Ext2LpB"
        logical_switch_name: "VLAN-Ext2Ls"
        admin_state: UP
        state: "present"
      register: lsp_T0_EXT2b


    - name: Create logical router port on T0 router EN1 to interconnect uplink VLAN EXT1
      nsxt_logical_router_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: VLAN-Ext1LsEN1
        resource_type: LogicalRouterUpLinkPort
        logical_router_id: "{{t0.id}}"
        edge_cluster_member_index: [2]
        linked_logical_switch_port_id:
          target_type: LogicalPort
          target_id:  "{{lsp_T0_EXT1a.id }}"
        subnets:
        - ip_addresses:
          - 192.168.254.11
          prefix_length: 29
        state: "present"

    - name: Create logical router port on T0 router EN2 to interconnect uplink VLAN EXT2
      nsxt_logical_router_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: VLAN-Ext2LsEN2
        resource_type: LogicalRouterUpLinkPort
        logical_router_id: "{{t0.id}}"
        edge_cluster_member_index: [3]
        linked_logical_switch_port_id:
          target_type: LogicalPort
          target_id:  "{{lsp_T0_EXT2a.id }}"
        subnets:
        - ip_addresses:
          - 192.168.254.19
          prefix_length: 29
        state: "present"


    - name: Create logical router port on T0 router EN2 to interconnect uplink VLAN EXT1
      nsxt_logical_router_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: VLAN-Ext1LsEN2
        resource_type: LogicalRouterUpLinkPort
        logical_router_id: "{{t0.id}}"
        edge_cluster_member_index: [3]
        linked_logical_switch_port_id:
          target_type: LogicalPort
          target_id:  "{{lsp_T0_EXT1b.id }}"
        subnets:
        - ip_addresses:
          - 192.168.254.12
          prefix_length: 29
        state: "present"

    - name: Create logical router port on T0 router EN1 to interconnect uplink VLAN EXT2
      nsxt_logical_router_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: VLAN-Ext2LsEN1
        resource_type: LogicalRouterUpLinkPort
        logical_router_id: "{{t0.id}}"
        edge_cluster_member_index: [2]
        linked_logical_switch_port_id:
          target_type: LogicalPort
          target_id:  "{{lsp_T0_EXT2b.id }}"
        subnets:
        - ip_addresses:
          - 192.168.254.20
          prefix_length: 29
        state: "present"


    - name: Read BGP configuration on T0 router
      uri:
        method: GET
        url: https://{{hostname}}/api/v1/logical-routers/{{t0.id}}/routing/bgp
        user: "admin"
        password: "VMware1!"
        body_format: json
        force_basic_auth: yes
        validate_certs: no
      register: result2


    - name: Enable BGP on T0 router
      uri:
        method: PUT
        url: https://{{hostname}}/api/v1/logical-routers/{{t0.id}}/routing/bgp
        user: "admin"
        password: "VMware1!"
        body:
          resource_type: BgpConfig
          description: "Uplink to external"
          display_name: "Uplink to external"
          as_num: 65003
          graceful_restart: false
          enabled: true
          ecmp: true
          _revision: "{{result2.json._revision}}"
        body_format: json
        force_basic_auth: yes
        validate_certs: no

    - name: Read BGP configuration on T0 router
      uri:
        method: GET
        url: https://{{hostname}}/api/v1/logical-routers/{{t0.id}}/routing/bgp
        user: "admin"
        password: "VMware1!"
        body_format: json
        force_basic_auth: yes
        validate_certs: no
      register: result3


    - name: Configure BGP peering to CSR-01a
      uri:
        method: POST
        url: https://{{hostname}}/api/v1/logical-routers/{{t0.id}}/routing/bgp/neighbors
        user: "admin"
        password: "VMware1!"
        body:
          display_name: neighbor1
          neighbor_address: "192.168.254.9"
          remote_as_num: 65002
          address_families:
          -
            type: IPV4_UNICAST
            enabled: true
          source_addresses:
            - 192.168.254.11
            - 192.168.254.12
        body_format: json
        force_basic_auth: yes
        validate_certs: no


    - name: Configure BGP peering to CSR-02a
      uri:
        method: POST
        url: https://{{hostname}}/api/v1/logical-routers/{{t0.id}}/routing/bgp/neighbors
        user: "admin"
        password: "VMware1!"
        body:
          display_name: neighbor2
          neighbor_address: "192.168.254.17"
          remote_as_num: 65002
          address_families:
          -
            type: IPV4_UNICAST
            enabled: true
          source_addresses:
            - 192.168.254.19
            - 192.168.254.20
        body_format: json
        force_basic_auth: yes
        validate_certs: no


    - name: Read routing redistribution configuration on T0 router
      uri:
        method: GET
        url: https://{{hostname}}/api/v1/logical-routers/{{t0.id}}/routing/redistribution
        user: "admin"
        password: "VMware1!"
        body_format: json
        force_basic_auth: yes
        validate_certs: no
      register: T0red


    - name: Enable routing redistribution on T0 router
      uri:
        method: PUT
        url:  https://{{hostname}}/api/v1/logical-routers/{{t0.id}}/routing/redistribution
        user: "admin"
        password: "VMware1!"
        body:
          resource_type: "RedistributionConfig"
          bgp_enabled: true
          _revision: "{{T0red.json._revision}}"
        body_format: json
        force_basic_auth: yes
        validate_certs: no


    - name: Read routing redistribution rules configuration on T0 router
      uri:
        method: GET
        url: https://{{hostname}}/api/v1/logical-routers/{{t0.id}}/routing/redistribution/rules
        user: "admin"
        password: "VMware1!"
        body_format: json
        force_basic_auth: yes
        validate_certs: no
      register: T0redrules

    - name: Add routing redistribution rule ALL on T0 router
      uri:
        method: PUT
        url:  https://{{hostname}}/api/v1/logical-routers/{{t0.id}}/routing/redistribution/rules
        user: "admin"
        password: "VMware1!"
        body:
          resource_type: "RedistributionRuleList"
          rules:
          - display_name: everything-into-bgp
            description: BGP learns all routes
            destination: BGP
            sources:
            - STATIC
            - NSX_CONNECTED
            - NSX_STATIC
            - TIER0_NAT
            - TIER1_NAT
            - TIER1_LB_VIP
            - TIER1_LB_SNAT
          _revision: "{{T0redrules.json._revision}}"
        body_format: json
        force_basic_auth: yes
        validate_certs: no



    - name: Add IP Block for K8s PODs
      uri:
        method: POST
        url:  https://{{hostname}}/api/v1/pools/ip-blocks
        user: "admin"
        password: "VMware1!"
        body:
          display_name: PODs-IP-Block
          description: K8s pods IP will be allocated from this pool
          cidr: 172.20.0.0/16
        body_format: json
        force_basic_auth: yes
        validate_certs: no
        status_code: 201

    - name: Add IP Pool for K8s SNATs
      uri:
        method: POST
        url:  https://{{hostname}}/api/v1/pools/ip-pools
        user: "admin"
        password: "VMware1!"
        body:
          display_name: K8s-Snat-Pool
          subnets:
          - allocation_ranges:
            - start: 172.16.200.10
              end: 172.16.200.20
            gateway_ip: 172.16.200.1
            cidr: 172.16.200.0/24
        body_format: json
        force_basic_auth: yes
        validate_certs: no
        status_code: 201

