---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - livefire_answerfile.yml
  tasks:
    - name: Collect T0 Router-id
      uri:
        method: GET
        url: https://{{hostname}}/api/v1/logical-routers
        user: "admin"
        password: "VMware1!"
        body_format: json
        force_basic_auth: yes
        validate_certs: no
      register: result


    - name: Read BGP configuration on T0 router
      uri:
        method: GET
        url: https://{{hostname}}/api/v1/logical-routers/{{result.json.results[0].id}}/routing/bgp
        user: "admin"
        password: "VMware1!"
        body_format: json
        force_basic_auth: yes
        validate_certs: no
      register: result2


    - name: Enable BGP on T0 router
      uri:
        method: PUT
        url: https://{{hostname}}/api/v1/logical-routers/{{result.json.results[0].id}}/routing/bgp
        user: "admin"
        password: "VMware1!"
        body:
          resource_type: BgpConfig
          description: "Uplink to external"
          display_name: "Uplink to external"
          as_num: 65001
          graceful_restart: false
          enabled: true
          ecmp: true
          _revision: "{{result2.json._revision}}"
        body_format: json
        force_basic_auth: yes
        validate_certs: no

    - name: Read BGP configuration on T0 router
      uri:
        method: GET
        url: https://{{hostname}}/api/v1/logical-routers/{{result.json.results[0].id}}/routing/bgp
        user: "admin"
        password: "VMware1!"
        body_format: json
        force_basic_auth: yes
        validate_certs: no
      register: result3


    - name: Configure BGP peering to CSR-01a
      uri:
        method: POST
        url: https://{{hostname}}/api/v1/logical-routers/{{result.json.results[0].id}}/routing/bgp/neighbors
        user: "admin"
        password: "VMware1!"
        body:
          display_name: neighbor1
          neighbor_address: "192.168.254.9"
          remote_as_num: 65002
          address_families: 
          - 
            type: IPV4_UNICAST
            enabled: true
          source_addresses:
            - 192.168.254.13
            - 192.168.254.14
        body_format: json
        force_basic_auth: yes
        validate_certs: no


    - name: Configure BGP peering to CSR-02a
      uri:
        method: POST
        url: https://{{hostname}}/api/v1/logical-routers/{{result.json.results[0].id}}/routing/bgp/neighbors
        user: "admin"
        password: "VMware1!"
        body:
          display_name: neighbor2
          neighbor_address: "192.168.254.17"
          remote_as_num: 65002
          address_families:
          -
            type: IPV4_UNICAST
            enabled: true
          source_addresses:
            - 192.168.254.21
            - 192.168.254.22
        body_format: json
        force_basic_auth: yes
        validate_certs: no


        
    - name: "Create Overlay Logical Switches for 4 Tiers Application"
      nsxt_logical_switches:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "{{item.display_name}}"
        replication_mode: SOURCE
        admin_state: UP
        transport_zone_name: "{{overlay_transportzones[0].display_name}}"
        state: "present"
      with_items:
        - "{{application_overlays}}"


    - name: Create T1 logical router
      nsxt_logical_routers:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "t1-tenant1"
        edge_cluster_name: edge-cluster-1-SiteA
        router_type: TIER1
        high_availability_mode: ACTIVE_STANDBY
        state: "present"
      register: T1


    - name: Create logical port on Overlay LS to connect the T1 router
      nsxt_logical_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "{{item.display_name}}_lsp"
        logical_switch_name: "{{item.display_name}}"
        admin_state: UP
        state: "present"
      with_items:
        - "{{application_overlays}}"
      register: overlay_lsp


    - name: Create logical router port for web LS
      uri:
        method: POST
        status_code: 201
        url: https://{{hostname}}/api/v1/logical-router-ports
        user: "admin"
        password: "VMware1!"
        body:
          resource_type: LogicalRouterDownLinkPort
          logical_router_id: "{{T1.id}}"
          linked_logical_switch_port_id:
           target_type: LogicalPort
           target_id: "{{overlay_lsp.results[0].id}}"
          subnets:
           - ip_addresses:
             - "172.16.10.1"
             prefix_length: 24
        force_basic_auth: yes
        validate_certs: no
        body_format: json


    - name: Create logical router port for app LS
      uri:
        method: POST
        status_code: 201
        url: https://{{hostname}}/api/v1/logical-router-ports
        user: "admin"
        password: "VMware1!"
        body:
          resource_type: LogicalRouterDownLinkPort
          logical_router_id: "{{T1.id}}"
          linked_logical_switch_port_id:
           target_type: LogicalPort
           target_id: "{{overlay_lsp.results[1].id}}"
          subnets:
           - ip_addresses:
             - "172.16.20.1"
             prefix_length: 24
        force_basic_auth: yes
        validate_certs: no
        body_format: json


    - name: Create logical router port for db LS
      uri:
        method: POST
        status_code: 201
        url: https://{{hostname}}/api/v1/logical-router-ports
        user: "admin"
        password: "VMware1!"
        body:
          resource_type: LogicalRouterDownLinkPort
          logical_router_id: "{{T1.id}}"
          linked_logical_switch_port_id:
           target_type: LogicalPort
           target_id: "{{overlay_lsp.results[2].id}}"
          subnets:
           - ip_addresses:
             - "172.16.30.1"
             prefix_length: 24
        force_basic_auth: yes
        validate_certs: no
        body_format: json



    - name: Create logical router port on TO to connet T1
      uri:
        method: POST
        status_code: 201
        url: https://{{hostname}}/api/v1/logical-router-ports
        user: "admin"
        password: "VMware1!"
        body:
          resource_type: LogicalRouterLinkPortOnTIER0
          logical_router_id: "{{result.json.results[0].id}}"
        force_basic_auth: yes
        validate_certs: no
        body_format: json
      register: T0toT1lsp

     

    - name: Create logical router port on T1 to connect T0
      uri:
        method: POST
        status_code: 201
        url: https://{{hostname}}/api/v1/logical-router-ports
        user: "admin"
        password: "VMware1!"
        body:
          resource_type: LogicalRouterLinkPortOnTIER1
          logical_router_id: "{{T1.id}}"
          linked_logical_router_port_id:
           target_type: LogicalPort
           target_id: "{{T0toT1lsp.json.id}}"
        force_basic_auth: yes
        validate_certs: no
        body_format: json
  


    - name: Read routing advertisement configuration on T1 router
      uri:
        method: GET
        url: https://{{hostname}}/api/v1/logical-routers/{{T1.id}}/routing/advertisement
        user: "admin"
        password: "VMware1!"
        body_format: json
        force_basic_auth: yes
        validate_certs: no
      register: T1adv



    - name: Enable routing advertisement on T1 router
      uri:
        method: PUT
        url:  https://{{hostname}}/api/v1/logical-routers/{{T1.id}}/routing/advertisement
        user: "admin"
        password: "VMware1!"
        body:
          resource_type: "AdvertisementConfig"
          advertise_nsx_connected_routes: true
          advertise_static_routes: true
          advertise_nat_routes: true
          advertise_lb_vip: true
          advertise_lb_snat_ip: true
          enabled: true
          _revision: "{{T1adv.json._revision}}"
        body_format: json
        force_basic_auth: yes
        validate_certs: no




    - name: Read routing redistribution configuration on T0 router
      uri:
        method: GET
        url: https://{{hostname}}/api/v1/logical-routers/{{result.json.results[0].id}}/routing/redistribution
        user: "admin"
        password: "VMware1!"
        body_format: json
        force_basic_auth: yes
        validate_certs: no
      register: T0red


    - name: Enable routing redistribution on T0 router
      uri:
        method: PUT
        url:  https://{{hostname}}/api/v1/logical-routers/{{result.json.results[0].id}}/routing/redistribution
        user: "admin"
        password: "VMware1!"
        body:
          resource_type: "RedistributionConfig"
          bgp_enabled: true
          _revision: "{{T0red.json._revision}}"
        body_format: json
        force_basic_auth: yes
        validate_certs: no


    - name: Read routing redistribution rules configuration on T0 router
      uri:
        method: GET
        url: https://{{hostname}}/api/v1/logical-routers/{{result.json.results[0].id}}/routing/redistribution/rules
        user: "admin"
        password: "VMware1!"
        body_format: json
        force_basic_auth: yes
        validate_certs: no
      register: T0redrules

    - name: Add routing redistribution rule ALL on T0 router
      uri:
        method: PUT
        url:  https://{{hostname}}/api/v1/logical-routers/{{result.json.results[0].id}}/routing/redistribution/rules
        user: "admin"
        password: "VMware1!"
        body:
          resource_type: "RedistributionRuleList"
          rules:
          - display_name: everything-into-bgp
            description: BGP learns all routes
            destination: BGP
            sources:
            - STATIC
            - NSX_CONNECTED
            - NSX_STATIC
            - TIER0_NAT
            - TIER1_NAT
            - TIER1_LB_VIP
            - TIER1_LB_SNAT
          _revision: "{{T0redrules.json._revision}}"
        body_format: json
        force_basic_auth: yes
        validate_certs: no

