- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Create logical router
      nsxt_logical_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "logical_port_1"
        logical_switch_name: test_switch
        attachment:
          attachment_type: VIF
          id: vif1
        admin_state: UP
        state: "present"
