- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Deploy controller
      nsxt_controllers:
          hostname: "{{hostname}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: False
          deployment_requests:
          - roles:
            - CONTROLLER
            form_factor: "MEDIUM"
            user_settings:
              cli_password: "Admin!23Admin"
              root_password: "Admin!23Admin"
            deployment_config:
              placement_type: VsphereClusterNodeVMDeploymentConfig
              vc_id: "2e582544-b6e6-446c-999c-5b5ccf7f5e80"
              management_network_id: "network-44"
              hostname: "controller2.vmware.com"
              compute_id: "domain-c49"
              storage_id: "datastore-43"
              default_gateway_addresses:
              - 10.112.203.253
              management_port_subnets:
              - ip_addresses:
                - 10.112.201.25
                prefix_length: "19"
          clustering_config:
            clustering_type: ControlClusteringConfig
            shared_secret: "123456"
            join_to_existing_cluster: false
          #node_id: b56f3b3d-51e1-4177-ac02-bd2d14f1d667
          state: present
